Working on ci/cd errors

diff --git a/server-ce/Dockerfile-base b/server-ce/Dockerfile-base
--- a/server-ce/Dockerfile-base
+++ b/server-ce/Dockerfile-base
@@ -49,121 +49,79 @@ RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
 #     --build-arg TEXLIVE_MIRROR=https://ctan.crest.fr/tex-archive/systems/texlive/tlnet \
 #     -f Dockerfile-base -t sharelatex/sharelatex-base .
 ARG TEXLIVE_MIRROR=https://mirror.ox.ac.uk/sites/ctan.org/systems/texlive/tlnet
+ARG TEXLIVE_FALLBACK_MIRRORS="https://mirror.ctan.org/systems/texlive/tlnet https://ctan.math.utah.edu/ctan/tex-archive/systems/texlive/tlnet"
 
-RUN mkdir /install-tl-unx \
-&&  wget --quiet https://tug.org/texlive/files/texlive.asc \
-&&  gpg --import texlive.asc \
-&&  rm texlive.asc \
-&&  wget --quiet ${TEXLIVE_MIRROR}/install-tl-unx.tar.gz \
-&&  wget --quiet ${TEXLIVE_MIRROR}/install-tl-unx.tar.gz.sha512 \
-&&  wget --quiet ${TEXLIVE_MIRROR}/install-tl-unx.tar.gz.sha512.asc \
-&&  gpg --verify install-tl-unx.tar.gz.sha512.asc \
-&&  sha512sum -c install-tl-unx.tar.gz.sha512 \
-&&  tar -xz -C /install-tl-unx --strip-components=1 -f install-tl-unx.tar.gz \
-&&  rm install-tl-unx.tar.gz* \
-&&  echo "tlpdbopt_autobackup 0" >> /install-tl-unx/texlive.profile \
-&&  echo "tlpdbopt_install_docfiles 0" >> /install-tl-unx/texlive.profile \
-&&  echo "tlpdbopt_install_srcfiles 0" >> /install-tl-unx/texlive.profile \
-&&  echo "selected_scheme scheme-basic" >> /install-tl-unx/texlive.profile \
-    \
-&&  /install-tl-unx/install-tl \
-      -profile /install-tl-unx/texlive.profile \
-      -repository ${TEXLIVE_MIRROR} \
-    \
-&&  $(find /usr/local/texlive -name tlmgr) path add \
-&&  tlmgr install --repository ${TEXLIVE_MIRROR} \
+RUN set -eux; \
+            mkdir /install-tl-unx; \
+            wget --quiet https://tug.org/texlive/files/texlive.asc; \
+            gpg --batch --import texlive.asc; \
+            rm texlive.asc; \
+            SELECTED_MIRROR=""; \
+            for mirror in "${TEXLIVE_MIRROR}" ${TEXLIVE_FALLBACK_MIRRORS}; do \
+                  echo "Trying TeX Live mirror: ${mirror}"; \
+                  if wget --tries=3 --timeout=30 --waitretry=5 --retry-connrefused --quiet -O install-tl-unx.tar.gz "${mirror}/install-tl-unx.tar.gz" \
+                        && wget --tries=3 --timeout=30 --waitretry=5 --retry-connrefused --quiet -O install-tl-unx.tar.gz.sha512 "${mirror}/install-tl-unx.tar.gz.sha512" \
+                        && wget --tries=3 --timeout=30 --waitretry=5 --retry-connrefused --quiet -O install-tl-unx.tar.gz.sha512.asc "${mirror}/install-tl-unx.tar.gz.sha512.asc" \
+                        && gpg --batch --verify install-tl-unx.tar.gz.sha512.asc install-tl-unx.tar.gz.sha512 \
+                        && sha512sum -c install-tl-unx.tar.gz.sha512; then \
+                        SELECTED_MIRROR="${mirror}"; \
+                        break; \
+                  fi; \
+                  rm -f install-tl-unx.tar.gz install-tl-unx.tar.gz.sha512 install-tl-unx.tar.gz.sha512.asc; \
+            done; \
+            if [ -z "${SELECTED_MIRROR}" ]; then \
+                  echo "Unable to fetch and verify TeX Live installer from all configured mirrors"; \
+                  exit 1; \
+            fi; \
+            echo "${SELECTED_MIRROR}" > /tmp/texlive-mirror; \
+            tar -xz -C /install-tl-unx --strip-components=1 -f install-tl-unx.tar.gz; \
+            rm -f install-tl-unx.tar.gz install-tl-unx.tar.gz.sha512 install-tl-unx.tar.gz.sha512.asc; \
+            echo "tlpdbopt_autobackup 0" >> /install-tl-unx/texlive.profile; \
+            echo "tlpdbopt_install_docfiles 0" >> /install-tl-unx/texlive.profile; \
+            echo "tlpdbopt_install_srcfiles 0" >> /install-tl-unx/texlive.profile; \
+            echo "selected_scheme scheme-basic" >> /install-tl-unx/texlive.profile; \
+            /install-tl-unx/install-tl \
+                  -profile /install-tl-unx/texlive.profile \
+                  -repository "${SELECTED_MIRROR}"; \
+            TLMGR_BIN="$(find /usr/local/texlive -name tlmgr | head -n 1)"; \
+            "${TLMGR_BIN}" path add; \
+            tlmgr install --repository "${SELECTED_MIRROR}" \
       latexmk \
       texcount \
       synctex \
       etoolbox \
-      xetex \
-&&  tlmgr path add \
-&&  rm -rf /install-tl-unx
+                  xetex; \
+            tlmgr path add; \
+            rm -rf /install-tl-unx
 
 # Install commonly-used LaTeX packages to reduce compilation time
 # This provides a good baseline for most academic and technical documents
 # Users can still install additional packages via the auto-install mechanism
 # -----------------------------------------------------------------
-RUN tlmgr install --repository ${TEXLIVE_MIRROR} \
-      amsfonts \
-      amsmath \
-      amssymb \
-      babel \
-      babelbib \
-      beamer \
-      bidi \
-      bookmark \
-      booktabs \
-      breakurl \
-      caption \
-      cite \
-      color \
-      colortbl \
-      csquotes \
-      enumitem \
-      eso-pic \
-      etoc \
-      fancyhdr \
-      fancyvrb \
-      fontspec \
-      float \
-      fontawesome5 \
-      geometry \
-      glossaries \
-      graphicx \
-      grffile \
-      graphics \
-      hyperref \
-      iftex \
-      inputenc \
-      kantlipsum \
-      lastpage \
-      listings \
-      lmodern \
-      logreq \
-      makechap \
-      makeindex \
-      marginnote \
-      marvosym \
-      mathtools \
-      microtype \
-      minted \
-      natbib \
-      notoccite \
-      palatino \
-      paralist \
-      parskip \
-      pdfpages \
-      pgf \
-      polyglossia \
-      preview \
-      ragged2e \
-      soul \
-      splitindex \
-      subfig \
-      table \
-      template \
-      texshade \
-      tgbonum \
-      tgcadm \
-      tgcursor \
-      tgheros \
-      tgpagella \
-      tikz \
-      tikzmark \
-      titlesec \
-      tocloft \
-      todonotes \
-      unicode-math \
-      units \
-      url \
-      utopia \
-      varwidth \
-      verbatim \
-      wasysym \
-      wrapfig \
-      xcolor \
-      xkeyval
+RUN set -eux; \
+            TEXLIVE_REPO="${TEXLIVE_MIRROR}"; \
+            if [ -f /tmp/texlive-mirror ]; then TEXLIVE_REPO="$(cat /tmp/texlive-mirror)"; fi; \
+            TEXLIVE_PACKAGES=" \
+                  amsfonts amsmath amssymb babel babelbib beamer bidi bookmark booktabs breakurl caption cite color colortbl csquotes enumitem eso-pic etoc \
+                  fancyhdr fancyvrb fontspec float fontawesome5 geometry glossaries graphicx grffile graphics hyperref iftex inputenc kantlipsum lastpage \
+                  listings lmodern logreq makechap makeindex marginnote marvosym mathtools microtype minted natbib notoccite palatino paralist parskip \
+                  pdfpages pgf polyglossia preview ragged2e soul splitindex subfig table template texshade tgbonum tgcadm tgcursor tgheros tgpagella \
+                  tikz tikzmark titlesec tocloft todonotes unicode-math units url utopia varwidth verbatim wasysym wrapfig xcolor xkeyval"; \
+            INSTALL_OK=""; \
+            for repo in "${TEXLIVE_REPO}" ${TEXLIVE_FALLBACK_MIRRORS}; do \
+                  echo "Installing TeX packages from ${repo}"; \
+                  if tlmgr install --no-execute-actions --repository "${repo}" ${TEXLIVE_PACKAGES}; then \
+                        INSTALL_OK="1"; \
+                        break; \
+                  fi; \
+            done; \
+            if [ -z "${INSTALL_OK}" ]; then \
+                  echo "Failed to install common TeX packages from all configured repositories"; \
+                  exit 1; \
+            fi; \
+            mktexlsr || true; \
+            updmap-sys || true; \
+            rm -f /tmp/texlive-mirror
 
 
 # Set up overleaf user and home directory
